### ISSUE TITLE
Cannot be run on Python 3.6

### ISSUE THREAD

**Issue by 040840308** [TUIlmenauAMS/ASP#1]
I tried to run testFiles/mt_test.py on python 3.6, however, failed, with the following errors:

"C:\Program Files\Python\python3\python.exe" "C:/GeneralStoreage/PyCharm-workspace/Audio Processing Learning/src/testFiles/mt_test.py"
Slow BLAS will be used...
PQMF class was not found. 
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/GeneralStoreage/PyCharm-workspace/Audio Processing Learning/src/testFiles/mt_test.py", line 41, in <module>
    pm = TF.PsychoacousticModel(N = N, fs = fs, nfilts = 60)
  File "C:\GeneralStoreage\PyCharm-workspace\Audio Processing Learning\src\TFMethods.py", line 790, in __init__
    self.W = self.mX2Bark(type)
  File "C:\GeneralStoreage\PyCharm-workspace\Audio Processing Learning\src\TFMethods.py", line 813, in mX2Bark
    W = self.fft2bark_rasta()
  File "C:\GeneralStoreage\PyCharm-workspace\Audio Processing Learning\src\TFMethods.py", line 880, in fft2bark_rasta
    W[i,0:(nfft/2)+1] = (np.round(binbarks/step_barks)== i)
TypeError: slice indices must be integers or None or have an __index__ method

Can this run python 3? Or I missed some necessary packages?

**Comment by gdtschuller** [comment]
Thank you for your comment. Yes, indeed, right now it only runs with Python2.7. We will update it for Python 3.6.
